#!/bin/bash
# Sets up a persistent local code-signing identity for Rokuga development.
#
# Why: the default build uses ad-hoc signing, which works out of the box but
# resets macOS privacy permissions (Screen Recording etc.) on every rebuild.
# This script creates a self-signed "Rokuga Dev" certificate — no Apple ID
# required — so the signing identity stays stable across builds and you only
# grant permissions once.
#
# Usage: ./scripts/setup-dev-signing.sh
set -euo pipefail

IDENTITY="Rokuga Dev"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_XCCONFIG="$REPO_ROOT/Configs/Signing.local.xcconfig"
KEYCHAIN="$HOME/Library/Keychains/login.keychain-db"

if security find-identity -v -p codesigning 2>/dev/null | grep -q "\"$IDENTITY\""; then
  echo "✓ '$IDENTITY' certificate already exists"
else
  echo "Creating self-signed '$IDENTITY' certificate..."
  echo "  (a keychain dialog may appear — approve it with your login password)"
  DIR=$(mktemp -d)
  trap 'rm -rf "$DIR"' EXIT
  cat > "$DIR/conf" <<'EOF'
[req]
distinguished_name=dn
x509_extensions=ext
prompt=no
[dn]
CN=Rokuga Dev
[ext]
keyUsage=critical,digitalSignature
extendedKeyUsage=critical,codeSigning
basicConstraints=critical,CA:FALSE
EOF
  openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
    -keyout "$DIR/key.pem" -out "$DIR/cert.pem" -config "$DIR/conf" 2>/dev/null
  openssl pkcs12 -export -legacy -out "$DIR/dev.p12" -inkey "$DIR/key.pem" \
    -in "$DIR/cert.pem" -passout pass:rokugatmp 2>/dev/null \
    || openssl pkcs12 -export -out "$DIR/dev.p12" -inkey "$DIR/key.pem" \
       -in "$DIR/cert.pem" -passout pass:rokugatmp
  security import "$DIR/dev.p12" -k "$KEYCHAIN" -P rokugatmp -T /usr/bin/codesign
  security add-trusted-cert -r trustRoot -p codeSign -k "$KEYCHAIN" "$DIR/cert.pem"
  echo "✓ Certificate created and trusted for code signing"
fi

cat > "$LOCAL_XCCONFIG" <<EOF
// Local developer override — NOT committed (gitignored).
// Generated by scripts/setup-dev-signing.sh
CODE_SIGN_IDENTITY = $IDENTITY
EOF
echo "✓ Wrote Configs/Signing.local.xcconfig"

if command -v xcodegen >/dev/null 2>&1; then
  (cd "$REPO_ROOT" && xcodegen generate >/dev/null)
  echo "✓ Regenerated Xcode project"
fi

echo ""
echo "Done. Builds now sign as '$IDENTITY'."
echo "On the first build, click 'Always Allow' when codesign asks for keychain access."
